/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Tim' at '8/26/18 3:15 PM' with Gradle 2.10
 *
 * @author Tim, @date 8/26/18 3:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
